version: '3.4'

services:
  index:
    image: index
    build:
      context: .
    ports:
      - 4000:4000
    environment:
      WORKER_URL: http://worker:8080
      SCW_ACCESS_KEY: ${MINIO_ROOT_USER}
      SCW_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: ${S3_BUCKET}
      SCW_DEFAULT_REGION: fr-par
      PYPI_INDEX: pypi.org
    networks:
      - sls-pypi-net
  worker:
    image: pypi_worker
    build:
      context: ./worker
    environment:
      SCW_ACCESS_KEY: ${MINIO_ROOT_USER}
      SCW_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: ${S3_BUCKET}
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sls-pypi-net
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION_NAME: fr-par
    entrypoint: sh
    command: -c 'mkdir -p /data/${S3_BUCKET} && minio server /data --console-address ":9001"'
    networks:
      - sls-pypi-net

networks:
  # We name the network for the e2e tests.
  sls-pypi-net:
    name: sls-pypi-net
